In [2]:
#Standardization
import pandas as pd 
import numpy as np
from sklearn.preprocessing import StandardScaler

In [7]:
data=np.array([1.3,2.1,4.5,6.5])
data
mean=np.mean(data)
std=np.std(data)
print(np.mean(data))
print(np.std(data))

3.6
2.046948949045872

In [8]:
#data-mean/std
scaled_data=(data-mean)/std
print("after scaling")
print(scaled_data)
print(np.mean(scaled_data))
print(np.std(scaled_data))

after scaling
[-1.12362353 -0.73279795  0.43967877  1.41674271]
0.0
0.9999999999999999

# Scaling

In [9]:
data=np.array([1.3,2.1,4.5,6.5])
data

dmin=np.min(data)
dmax=np.max(data)

# x-xmin/xmax-xmin formula
print((data-dmin)/(dmax-dmin))

[0.         0.15384615 0.61538462 1.        ]

In [10]:
data=data.reshape(-1,1)
from sklearn.preprocessing import MinMaxScaler
m=MinMaxScaler()
m.fit(data)
print(m.transform(data))

[[0.        ]
 [0.15384615]
 [0.61538462]
 [1.        ]]

In [11]:
s=np.array([0,0.15384615,0.61538462,1])
s
mean=np.mean(s)
std=np.std(s)
print(np.mean(s))
print(np.std(s))

0.4423076925
0.3936440298746028

In [12]:
#data-mean/std
scaled_data=(s-mean)/std
print("after scaling")
print(scaled_data)
print(np.mean(scaled_data))
print(np.std(scaled_data))

after scaling
[-1.12362353 -0.73279796  0.43967878  1.4167427 ]
0.0
0.9999999999999999

# Body fat

In [13]:
df=pd.read_csv("D:/Symbiosis/Dataset/Bodyfat.csv")
df

,Density,bodyfat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,1.0736,11.0,70,134.25,67.00,34.9,89.2,83.6,88.8,49.6,34.8,21.5,25.6,25.7,18.5
248,1.0236,33.6,72,201.00,69.75,40.9,108.5,105.0,104.5,59.6,40.8,23.2,35.2,28.6,20.1
249,1.0328,29.3,72,186.75,66.00,38.9,111.1,111.5,101.7,60.3,37.3,21.5,31.3,27.2,18.0
250,1.0399,26.0,72,190.75,70.50,38.9,108.3,101.3,97.8,56.0,41.6,22.7,30.5,29.4,19.8
251,1.0271,31.9,74,207.50,70.00,40.8,112.4,108.5,107.1,59.3,42.2,24.6,33.7,30.0,20.9

In [16]:
df.describe()

,Density,bodyfat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
count,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000
mean,1.055574,19.150794,44.884921,178.924405,70.148810,37.992063,100.824206,92.555952,99.904762,59.405952,38.590476,23.102381,32.273413,28.663889,18.229762
std,0.019031,8.368740,12.602040,29.389160,3.662856,2.430913,8.430476,10.783077,7.164058,5.249952,2.411805,1.694893,3.021274,2.020691,0.933585
min,0.995000,0.000000,22.000000,118.500000,29.500000,31.100000,79.300000,69.400000,85.000000,47.200000,33.000000,19.100000,24.800000,21.000000,15.800000
25%,1.041400,12.475000,35.750000,159.000000,68.250000,36.400000,94.350000,84.575000,95.500000,56.000000,36.975000,22.000000,30.200000,27.300000,17.600000
50%,1.054900,19.200000,43.000000,176.500000,70.000000,38.000000,99.650000,90.950000,99.300000,59.000000,38.500000,22.800000,32.050000,28.700000,18.300000
75%,1.070400,25.300000,54.000000,197.000000,72.250000,39.425000,105.375000,99.325000,103.525000,62.350000,39.925000,24.000000,34.325000,30.000000,18.800000
max,1.108900,47.500000,81.000000,363.150000,77.750000,51.200000,136.200000,148.100000,147.700000,87.300000,49.100000,33.900000,45.000000,34.900000,21.400000

In [17]:
from sklearn.preprocessing import MinMaxScaler
m=MinMaxScaler()
scaler=m.fit_transform(df)s
print(scaler)
print(np.mean(scaler))
print(np.std(scaler))
print(np.max(scaler))

[[0.66549605 0.25894737 0.01694915 ... 0.35643564 0.46043165 0.23214286]
 [0.7928007  0.12842105 0.         ... 0.28217822 0.56834532 0.42857143]
 [0.40737489 0.53263158 0.         ... 0.1980198  0.30215827 0.14285714]
 ...
 [0.33187006 0.61684211 0.84745763 ... 0.32178218 0.44604317 0.39285714]
 [0.39420544 0.54736842 0.84745763 ... 0.28217822 0.60431655 0.71428571]
 [0.28182616 0.67157895 0.88135593 ... 0.44059406 0.64748201 0.91071429]]
0.3961800913974409
0.20774142622659675
1.0000000000000002

In [19]:
from sklearn import preprocessing
data=preprocessing.StandardScaler().fit_transform(df)
print(data)
print(np.mean(data))
print(np.std(data))
print(np.max(data))

[[ 0.80164696 -0.82024615 -1.74007329 ... -0.09067593 -0.62671828
  -1.2125412 ]
 [ 1.56506057 -1.56257271 -1.81958344 ... -0.58814329  0.11707924
  -0.0319426 ]
 [-0.74623993  0.73624504 -1.81958344 ... -1.15193963 -1.71762131
  -1.74917692]
 ...
 [-1.19902317  1.2151654   2.15592399 ... -0.32282736 -0.72589128
  -0.24659689]
 [-0.82521375  0.8200561   2.15592399 ... -0.58814329  0.36501175
   1.68529172]
 [-1.49912369  1.52646364  2.31494429 ...  0.47312041  0.66253075
   2.86589032]]
3.905165432649757e-16
1.0
6.684808430933005

In [20]:
from sklearn.preprocessing import MinMaxScaler
m=MinMaxScaler()
scaler=m.fit_transform(df)
print(scaler)

[[0.66549605 0.25894737 0.01694915 ... 0.35643564 0.46043165 0.23214286]
 [0.7928007  0.12842105 0.         ... 0.28217822 0.56834532 0.42857143]
 [0.40737489 0.53263158 0.         ... 0.1980198  0.30215827 0.14285714]
 ...
 [0.33187006 0.61684211 0.84745763 ... 0.32178218 0.44604317 0.39285714]
 [0.39420544 0.54736842 0.84745763 ... 0.28217822 0.60431655 0.71428571]
 [0.28182616 0.67157895 0.88135593 ... 0.44059406 0.64748201 0.91071429]]